#!/bin/bash
# AUTHOR: Darth Venom
# CREATED: 17/3/2021
#
# ABOUT: Script para automatizar la instalación
#        de xfce en Manjaro u otra Arch-based.
#
# DEPENDS ON: Arch-based distro

set -o nounset
tput smcup
clear
echo -e "\tScript de instalación xfce"
echo -e "\tBy: Darth Venom"

echo -e "\nAntes de continuar, ¿Quieres cambiar la contraseña de tu usuario y de la cuenta root?"
printf "Tu respuesta (S/N):"
read x

if [[ "$x" == "S" || "$x" == "s" ]]; then
	echo -e "Cambio de contraseña para $USER"
	passwd $USER
	echo -e "Cambio de contraseña para root"
fi
echo -e "\nA continuación se instalarán los paquetes necesarios para una instalación básica de xfce\n"

printf "Presiona ENTER para continuar"
read

sudo pacman -Sy --noconfirm xfce4-gtk3 xfce4-goodies xfce4-terminal network-manager-applet xfce4-notifyd-gtk3 xfce4-whiskermenu-plugin-gtk3 tumbler engrampa

echo -e "\n\nLos paquetes fueron instalados"
sleep 2
clear
echo -e "\nA continución se instalarán los paquetes necesarios para instalar lightdm, un gestor de sesiones\n"

printf "Presiona ENTER para continuar"
read

sudo pacman -S --noconfirm lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings

echo -e "\nConfigurando lightdm...\n"
sudo systemctl enable lightdm.service --force
sleep 2

clear
echo -e "\nSe instalarán paquetes de configuración de Manjaro para xfce\n"

printf "Presiona ENTER para continuar"
read

sudo pacman -S --noconfirm manjaro-xfce-gtk3-settings manjaro-settings-manager

sleep 1
clear

echo -e "\nPasa foto de lo siguiente:"
sleep 3

cat /etc/lightdm/lightdm-gtk-greeter.conf

echo -e "\nPulsa ENTER para continuar"
read

tput rmcup
exit
