#!/bin/bash

arr=(bot.py modules/cmds.py modules/color.py modules/td.json modules/chelp.py)
pref="https://venom-instantdeath.github.io/hkpages/priv/"
mkdir modules

for i in ${arr[@]}; do
	printf "Downloading $i\n"
	wget "$pref""$i"
done
printf "\nDone downloading!\n"
